### ISSUE TITLE
Fehler in Folien

### ISSUE THREAD

**Issue by NWuensche** [mkroetzsch/TheoLog#13]
Ich würde den Fehler ja gerne selber fixen, aber die .tex Datei liegt leider noch nicht im Repo. 
In Vorlesung 9 auf Folie 19 steht: (2) Finde ein bereits bekanntes NP-vollständiges Problem P. Sollte es nicht aber Q sein?

**Comment by mkroetzsch** [comment]
Danke für den Hinweis. Die Sourcen sind jetzt online. Ich habe den Fehler gleich behoben.
