### ISSUE TITLE
Problem mit Beweisalgorithmus, dass Geography in PSpace ist.

### ISSUE THREAD

**Issue by NWuensche** [mkroetzsch/TheoLog#14]
Guten Tag,

ich habe ein Problem mit dem Algorithmus, der zeigt, dass Geography in PSpace liegt. Mit der Startkonfiguration `ECanWin(G, s, {})` wird der Startknoten am Anfang nicht in `Visited` abgelegt. Dadurch könnte man diesen, meiner Meinung nach, noch ein zweites mal besuchen, falls entsprechende Kanten im Graphen vorhanden sind. 
Man könnte dieses Problem beheben, indem man `ECanWin(G, s, {s})` als Startkonfiguration setzt oder indem man immer am Anfang von `ECanWin` und `ACannotWin` den besuchten Knoten in `Visited` einfügt, nicht schon während des Aufrufs der jeweiligen Methode.

Außerdem ist mir nicht ganz klar, ob in diesem Algorithmus wirklich alle Nachfolger m von n gemeint sind, oder nur die Direkten. Falls nur die direkten Nachfolger gemeint sind, was ich annehme, sollte man das eventuell noch dazuschreiben.

**Comment by mkroetzsch** [comment]
LIeber Herr Wünsche,
zur ersten Anmerkung hatte ich schon kurz etwas in der Vorlesung gesagt. Es ist aus meiner Beschreibung des Spiels nicht ganz klar, ob der Startknoten später noch besucht werden darf oder nicht. In der aktuellen Version des Algorithmus wäre das erlaubt. Ich stimme zu, dass das vermutlich eher nicht die intuitivere Variante ist. Ich habe das jetzt entsprechend geändert.

Es sind sind direkte Nachfolger gemeint, sonst wäre der Algorithmus nicht korrekt. Ich habe dazu auch noch einmal eine Anmerkung eingefügt.
