### ISSUE TITLE
Probeklausuren

### ISSUE THREAD

**Issue by JuKu** [mkroetzsch/TheoLog#21]
Ich wollte mal fragen, ob irgendwo Probeklausuren für TheoLog angeboten werden?

**Comment by exot** [comment]
Es wird bald eine Probeklausur veröffentlicht werden.  Diese wird dann an einem Vorlesungstermin vorgerechnet.

**Comment by exot** [comment]
Die Probeklausur (Musterklausur) ist jetzt auf der Kurswebseite freigegeben.
