### ISSUE TITLE
Fehler bei Beispiel zur Formelbereinigung

### ISSUE THREAD

**Issue by lllAlexanderlll** [mkroetzsch/TheoLog#22]
Vorelsung 16: Logisches Schließen (2), Folie 28 von 30 im Beispiel:
Das y in der bereinigten Formel liegt nach der Bereinigung gebunden und frei vor.
Eines müsste noch umbenannt werden.

**Comment by mkroetzsch** [comment]
In der Formel fehlten Klammern, die ich jetzt eingefügt habe. Jetzt bindet der initiale Quanto beide Vorkommen von y. Die Umbenennung kann damit so bleiben.
