### ISSUE TITLE
PCP - 5. Vorlesung 

### ISSUE THREAD

**Issue by hodasemi** [mkroetzsch/TheoLog#23]
Auf Folie 18 steht dass das 3. PCP nicht lösbar ist. Ich hab eine Lösung gefunden:

wenn man die paare nummeriert:
(1) [AA, B] 
(2) [BA, BAA]
(3) [ABA, A]

dann kann man mit der Folge: (1) (2) (2) (2) (3) 
das PCP lösen, so dass oben und unten jeweils 7 mal A und 4 mal B steht.

**Comment by portux** [comment]
Naja aber beim PCP geht es doch nicht darum, oben und unten die gleiche Anzahl von gleichen Symbolen zu erzeugen, sondern das entstandene Wort soll oben un unten gleich sein.
Bei dir wäre das obere Wort AA BA BA BA ABA und das untere B BAA BAA BAA A und das unterscheidet sich schon im ersten Symbol.

**Comment by hodasemi** [comment]
Gut ... das erklärt einiges
