### ISSUE TITLE
Falsches Modell, VL 17 Folie 18

### ISSUE THREAD

**Issue by SoulKa** [mkroetzsch/TheoLog#28]
Es müsste Multiplikation über _N_ sein, nicht Addiition über _N_:

für alle x.(x (+) 0) = 0

**Comment by mmarx** [comment]
Damit das tatsaechlich die Theorie der kommutativen Monoide wird, sollte die dritte Gleichung ∀x. (x ⊕ 0) = x lauten; dann ist auch (ℕ, +, 0) wieder ein Modell.
