### ISSUE TITLE
Lecture 1: total frame number

### ISSUE THREAD

**Issue by chlewe** [mkroetzsch/TheoLog#3]
On the slides of the first lecture the total frame number is wrongly set to 1.
I wanted to fix it through a pull request, but couldn't find the specific section in the source code.

**Comment by mkroetzsch** [comment]
(same as #4, which, of course, was submitted later)

The page numbers are compiled in automatically by LaTeX. I just would have had to run the PDF generation twice to get the correct numbers. Fixed in online PDFs.
