### ISSUE TITLE
WHILE-LOOP "Abkürzungen aus der Vorlesung"

### ISSUE THREAD

**Issue by ltsstar** [mkroetzsch/TheoLog#32]
In der Musterklausur wurde in Aufgabe 1 für LOOP die Möglichkeit angeboten "Abkürzungen aus der Vorlesung" zu benutzen.

In der Vorlesung wurden für Loop zwei Abkürzungen definiert:

- Addition / Subtraktion zweier Variablen
- IF x != 0 THEN P END

(Entsprechend dieser Abkürzungen wurde auch der größer-gleich Operator in der Besprechung der Musterklausur durch einen ungleich Operator ersetzt.)

(Habe ich eine in der VL definierte Abkürzung vergessen?)

Nun noch zwei Fragen der Klarheit wegen:
Sind die Abkürzungen aus LOOP auch für WHILE Programme erlaubt?
Dürfen LOOP Schleifen auch in WHILE Programmen genutzt werden (oder **muss** ich dann den Umweg über WHILE gehen)?

**Comment by mkroetzsch** [comment]
LOOP-Schleifen dürfen in WHILE verwendet werden. Dies wurde in Vorlesung 3, Folie 25 gezeigt und darf somit als Abkürzung gelten. In diesem Sinne dürfen auch andere für LOOP gezeigte Abkürzungen in WHILE genutzt werden.
