### ISSUE TITLE
Seitenzahlen stimmen nicht

### ISSUE THREAD

**Issue by JuKu** [mkroetzsch/TheoLog#4]
Bei den Folien steht immer "Seite x von 1". Die Zahl nach dem "von" stimmt quasi nicht, da muss die Zahl aller Seiten hin.

**Comment by mkroetzsch** [comment]
Das ist kein Fehler des Quellcodes sondern lag an falscher Übersetzung (LaTeX muss immer mehrmals laufen). Die PDFs im Netz sind korrekt.
