### ISSUE TITLE
Unifikationsalgorithmus VL18 Folie 17

### ISSUE THREAD

**Issue by sineme** [mkroetzsch/TheoLog#40]
Bei den Regeln zur Unifikation müsste man sagen, dass man sie nur anwenden kann, falls sie zu einer Änderung führen. Oder man müsste die Eliminierung einschränken, dass sie nur angewendet werden kann, falls x in G' vorkommt. Sonst könnte man die Eliminierung beliebig oft auf immer den selben Term anwenden ohne eine Änderung zu erzielen, wodurch der Algorithmus nicht terminieren würde.

Zum Beispiel ist das Unifikationsproblem
G={x≈r(), f(y)≈f(z() )}
noch nicht in gelöster Form, die Zerlegung würde noch zu einer Änderung führen und man kann die Eliminierung anwenden. Also kann man den Algorithmus anwenden, indem man die Eliminierung unendlich oft Auf x≈r() anwendet ohne das sich G ändert, wodurch der Algorithmus nicht terminieren würde.

**Comment by mkroetzsch** [comment]
Soweit ich erkennen kann, steht das schon da ("Wende die folgenden Umformungsregeln auf G an, bis keine Regel mehr zu einer Änderung führt"). Eventuell wurde das schon früher behoben.
