### ISSUE TITLE
bit order (lecture 1)

### ISSUE THREAD

**Issue by cooox** [mkroetzsch/TheoLog#6]
Judging from the reaction of the people around me, there seemed to be confusion with the bit order used for [the example in lecture 1](https://github.com/mkroetzsch/TheoLog/blob/54938ee869e918db0855b580b06c1dfc19ee140e/Vorlesungen/lecture-01.tex#L465-L470). I guess people are more used to read bits from right to left :smile: 

Ref: https://en.wikipedia.org/wiki/Bit_numbering

**Comment by mkroetzsch** [comment]
Das stimmt, aber wenn man die Bitordnung umkehrt, dann berechnet die TM nicht mehr den Nachfolger der eingegebenen Zahl. Stattdessen benötigt man eine neue TM, die einige weitere Zustände hat (wie muss sie aussehen?). Das schien mir für das Beispiel wiederum nicht so gut, da schwerer nachvollziehbar. Ich werde morgen nochmal eine Anmerkung dazu machen.
