### ISSUE TITLE
Wo sind die fertigen PDFs zu finden?

### ISSUE THREAD

**Issue by MaxMatti** [mkroetzsch/TheoLog#8]
In der README.md steht:

> Die fertigen PDFs aus dem Sommer 2017 sind online zu finden unter https://iccl.inf.tu-dresden.de/web/TheoLog2017.

Unter der angegebenen URL kann ich nur die PDFs der Übungen finden, nicht die der Vorlesungen. Wäre es möglich, die PDFs dort zu verlinken oder [in diesem GitHub-Repo zu veröffentlichen](https://help.github.com/articles/creating-releases/)?

**Comment by mmarx** [comment]
Am oberen Rand der Seite gibt es den Tab „Termine und Unterlagen,“ dort sind die PDFs verlinkt.
